FROM python:3.4-alpine3.7


RUN addgroup -S uwsgi && adduser -S -g uwsgi uwsgi
RUN pip install Flask==0.10.1 
RUN apk update; apk add --no-cache --virtual .build-deps gcc libc-dev musl  musl-dev linux-headers python3-dev build-base  pcre-dev
RUN pip install  uwsgi

WORKDIR /app
COPY app /app

EXPOSE 9090 9191
USER uwsgi
CMD ["uwsgi", "--http", "0.0.0.0:9090", "--wsgi-file", "/app/identidock.py", \
"--callable", "app", "--stats", "0.0.0.0:9191"]
