FROM python:3.4-alpine3.7

RUN apk add --update alpine-sdk  python-dev \
	pip install Flask==0.10.1 \
	pip install uwsgi

WORKDIR /app
COPY app /app

CMD ["uwsgi", "--plugins","python", "--enable-threads", "--http-socket", "0.0.0.0:9090", "--wsgi-file", "/app/identidock.py", \
"--callable", "app", "--stats", "0.0.0.0:9191"]
