proxy:
  image: identiproxy:0.1
  links:
    - identidock
  ports:
    - "80:80"
identidock:
  image: dockertonywu/identidock:0.1
  environment:
    ENV: PROD 
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis:3
